### ISSUE TITLE
trouble reading trees.pkl and allennlp version

### ISSUE THREAD

**Issue by PureLoveForyou** [NLP-Discourse-SoochowU/sota_end2end_parser#1]
I have trouble reading trees.pkl and running the code
furthermore, does this pre-trained-sota-model support Chinese or just English only?

I use below code to read
```
with open('trees.pkl', "rb") as f:
    data = pickle.load(f)
```
but got an error:
```
    data = pickle.load(f)
ModuleNotFoundError: No module named 'structure'
```
also, may I ask which allennlp version is proper to this code because I have touble running this module due to version incompatible. I have tried allennlp 1.0.0, 2.4.0 and other version of transfomers, but it won't work
```
Traceback (most recent call last):
  File "pipeline.py", line 334, in <module>
    seg_edus = do_seg(sents_dt, edu_dt)
  File "pipeline.py", line 182, in do_seg
    segmenter.cuda(CUDA_ID)
  File "/root/miniconda3/envs/NLP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 307, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/root/miniconda3/envs/NLP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/root/miniconda3/envs/NLP/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 149, in _apply
    self._flat_weights = [(lambda wn: getattr(self, wn) if hasattr(self, wn) else None)(wn) for wn in self._flat_weights_names]
  File "/root/miniconda3/envs/NLP/lib/python3.6/site-packages/torch/nn/modules/module.py", line 594, in __getattr__
    type(self).__name__, name))
AttributeError: 'GRU' object has no attribute '_flat_weights_names'
```

**Comment by zzlynx** [comment]
First of all, this project only supports English parsing. For the Chinese version, I will also build another one in about three months when I have free time.
Second, can you tell me which "trees.pkl" you wrote is referring to? I can't find your question.
Third, I pre-trained this model using an external server, and the environment was lost. I got you a model training environment based on the XLNet-base model. The two environments are similar, maybe you can refer to it.

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
absl-py                   0.9.0                    pypi_0    pypi
altair                    4.1.0                    pypi_0    pypi
argon2-cffi               20.1.0                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
base58                    2.0.1                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    3.1.5                    pypi_0    pypi
blinker                   1.4                      pypi_0    pypi
boto3                     1.14.37                  pypi_0    pypi
botocore                  1.17.37                  pypi_0    pypi
ca-certificates           2020.6.24                     0    defaults
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                pypi_0    pypi
cffi                      1.14.1                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cudatoolkit               9.2                           0    defaults
cudnn                     7.6.5                 cuda9.2_0    defaults
cycler                    0.10.0                   pypi_0    pypi
dataclasses               0.7                      py36_0    defaults
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
deprecated                1.2.12                   pypi_0    pypi
dill                      0.3.2                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
elasticsearch             7.8.1                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
enum-compat               0.0.3                    pypi_0    pypi
faiss                     1.5.3                    pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
fire                      0.3.1                    pypi_0    pypi
freetype                  2.10.2               h5ab3b9f_0    defaults
future                    0.18.2                   pypi_0    pypi
gensim                    4.1.2                    pypi_0    pypi
git-python                1.0.3                    pypi_0    pypi
gitdb                     4.0.5                    pypi_0    pypi
gitpython                 3.1.7                    pypi_0    pypi
google-auth               1.20.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
googleapis-common-protos  1.52.0                   pypi_0    pypi
grpcio                    1.31.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
intel-openmp              2020.1                      217    defaults
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    0.16.0                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.6                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
keras                     2.4.3                    pypi_0    pypi
kiwisolver                1.2.0                    pypi_0    pypi
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
lz4-c                     1.9.2                he6710b0_1    defaults
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.3.0                    pypi_0    pypi
megengine                 1.4.0                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.1.0            py36h23d657b_0    defaults
mkl_random                1.1.1            py36h0573a6f_0    defaults
mprop                     0.16.0                   pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
ninja                     1.10.0           py36hfd86e86_0    defaults
nlp                       0.4.0                    pypi_0    pypi
nltk                      3.5                      pypi_0    pypi
notebook                  6.1.1                    pypi_0    pypi
numpy                     1.19.1           py36hbc911f0_0    defaults
numpy-base                1.19.1           py36hfa32c7d_0    defaults
olefile                   0.46                     py36_0    defaults
opencv-python             4.5.3.56                 pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0    defaults
packaging                 20.4                     pypi_0    pypi
pandas                    1.1.0                    pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0            py36hb39fc2d_0    defaults
pip                       20.1.1                   py36_1    defaults
portalocker               2.0.0                    pypi_0    pypi
prometheus-client         0.8.0                    pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
protobuf                  3.12.4                   pypi_0    pypi
psutil                    5.7.0            py36h7b6447c_0    defaults
ptyprocess                0.6.0                    pypi_0    pypi
pyarrow                   1.0.0                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2    defaults
pydeck                    0.4.1                    pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.16.0                   pypi_0    pypi
python                    3.6.10               h7579374_2    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   1.5.0           py3.6_cuda9.2.148_cudnn7.6.3_0    pytorch
pytorch-lightning         0.8.5                    pypi_0    pypi
pytz                      2020.1                     py_0    defaults
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.2                   pypi_0    pypi
readline                  8.0                  h7b6447c_0    defaults
redispy                   3.0.0                    pypi_0    pypi
regex                     2020.7.14                pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rouge-score               0.0.4                    pypi_0    pypi
s3transfer                0.3.3                    pypi_0    pypi
sacrebleu                 1.4.13                   pypi_0    pypi
scikit-learn              0.23.1           py36h423224d_0    defaults
scipy                     1.5.2                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
seqeval                   0.0.12                   pypi_0    pypi
setuptools                49.2.1                   pypi_0    pypi
six                       1.15.0                     py_0    defaults
smart-open                5.2.1                    pypi_0    pypi
smmap                     3.0.4                    pypi_0    pypi
sqlite                    3.32.3               h62c20be_0    defaults
streamlit                 0.64.0                   pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
tensorboard               1.14.0                   pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow-datasets       3.2.1                    pypi_0    pypi
tensorflow-metadata       0.22.2                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.1                   pypi_0    pypi
toolz                     0.10.0                   pypi_0    pypi
torchvision               0.6.0                 py36_cu92    pytorch
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.48.2                   pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
transformers              3.0.2                    pypi_0    pypi
tzlocal                   2.1                      pypi_0    pypi
urllib3                   1.25.10                  pypi_0    pypi
validators                0.17.1                   pypi_0    pypi
watchdog                  0.10.3                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0    defaults
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xxhash                    2.0.0                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0    defaults
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h9ceee32_0    defaults


May you have a nice day! I will reply to your question further after I receive the email.

**Comment by PureLoveForyou** [comment]
> First of all, this project only supports English parsing. For the Chinese version, I will also build another one in about three months when I have free time. Second, can you tell me which "trees.pkl" you wrote is referring to? I can't find your question. Third, I pre-trained this model using an external server, and the environment was lost. I got you a model training environment based on the XLNet-base model. The two environments are similar, maybe you can refer to it.
> 
> Name Version Build Channel _libgcc_mutex 0.1 main defaults absl-py 0.9.0 pypi_0 pypi altair 4.1.0 pypi_0 pypi argon2-cffi 20.1.0 pypi_0 pypi astor 0.8.1 pypi_0 pypi attrs 19.3.0 pypi_0 pypi backcall 0.2.0 pypi_0 pypi base58 2.0.1 pypi_0 pypi blas 1.0 mkl defaults bleach 3.1.5 pypi_0 pypi blinker 1.4 pypi_0 pypi boto3 1.14.37 pypi_0 pypi botocore 1.17.37 pypi_0 pypi ca-certificates 2020.6.24 0 defaults cachetools 4.1.1 pypi_0 pypi certifi 2020.6.20 pypi_0 pypi cffi 1.14.1 pypi_0 pypi chardet 3.0.4 pypi_0 pypi click 7.1.2 pypi_0 pypi cudatoolkit 9.2 0 defaults cudnn 7.6.5 cuda9.2_0 defaults cycler 0.10.0 pypi_0 pypi dataclasses 0.7 py36_0 defaults decorator 4.4.2 pypi_0 pypi defusedxml 0.6.0 pypi_0 pypi deprecated 1.2.12 pypi_0 pypi dill 0.3.2 pypi_0 pypi docutils 0.15.2 pypi_0 pypi elasticsearch 7.8.1 pypi_0 pypi entrypoints 0.3 pypi_0 pypi enum-compat 0.0.3 pypi_0 pypi faiss 1.5.3 pypi_0 pypi filelock 3.0.12 pypi_0 pypi fire 0.3.1 pypi_0 pypi freetype 2.10.2 h5ab3b9f_0 defaults future 0.18.2 pypi_0 pypi gensim 4.1.2 pypi_0 pypi git-python 1.0.3 pypi_0 pypi gitdb 4.0.5 pypi_0 pypi gitpython 3.1.7 pypi_0 pypi google-auth 1.20.1 pypi_0 pypi google-auth-oauthlib 0.4.1 pypi_0 pypi googleapis-common-protos 1.52.0 pypi_0 pypi grpcio 1.31.0 pypi_0 pypi h5py 2.10.0 pypi_0 pypi idna 2.10 pypi_0 pypi importlib-metadata 1.7.0 pypi_0 pypi intel-openmp 2020.1 217 defaults ipykernel 5.3.4 pypi_0 pypi ipython 7.16.1 pypi_0 pypi ipython-genutils 0.2.0 pypi_0 pypi ipywidgets 7.5.1 pypi_0 pypi jedi 0.17.2 pypi_0 pypi jinja2 2.11.2 pypi_0 pypi jmespath 0.10.0 pypi_0 pypi joblib 0.16.0 py_0 defaults jpeg 9b h024ee3a_2 defaults jsonschema 3.2.0 pypi_0 pypi jupyter-client 6.1.6 pypi_0 pypi jupyter-core 4.6.3 pypi_0 pypi keras 2.4.3 pypi_0 pypi kiwisolver 1.2.0 pypi_0 pypi lcms2 2.11 h396b838_0 defaults ld_impl_linux-64 2.33.1 h53a641e_7 defaults libedit 3.1.20191231 h14c3975_1 defaults libffi 3.3 he6710b0_2 defaults libgcc-ng 9.1.0 hdf63c60_0 defaults libgfortran-ng 7.3.0 hdf63c60_0 defaults libpng 1.6.37 hbc83047_0 defaults libstdcxx-ng 9.1.0 hdf63c60_0 defaults libtiff 4.1.0 h2733197_1 defaults lz4-c 1.9.2 he6710b0_1 defaults markdown 3.2.2 pypi_0 pypi markupsafe 1.1.1 pypi_0 pypi matplotlib 3.3.0 pypi_0 pypi megengine 1.4.0 pypi_0 pypi mistune 0.8.4 pypi_0 pypi mkl 2020.1 217 defaults mkl-service 2.3.0 py36he904b0f_0 defaults mkl_fft 1.1.0 py36h23d657b_0 defaults mkl_random 1.1.1 py36h0573a6f_0 defaults mprop 0.16.0 pypi_0 pypi nbconvert 5.6.1 pypi_0 pypi nbformat 5.0.7 pypi_0 pypi ncurses 6.2 he6710b0_1 defaults ninja 1.10.0 py36hfd86e86_0 defaults nlp 0.4.0 pypi_0 pypi nltk 3.5 pypi_0 pypi notebook 6.1.1 pypi_0 pypi numpy 1.19.1 py36hbc911f0_0 defaults numpy-base 1.19.1 py36hfa32c7d_0 defaults olefile 0.46 py36_0 defaults opencv-python 4.5.3.56 pypi_0 pypi openssl 1.1.1g h7b6447c_0 defaults packaging 20.4 pypi_0 pypi pandas 1.1.0 pypi_0 pypi pandocfilters 1.4.2 pypi_0 pypi parso 0.7.1 pypi_0 pypi pathtools 0.1.2 pypi_0 pypi pexpect 4.8.0 pypi_0 pypi pickleshare 0.7.5 pypi_0 pypi pillow 7.2.0 py36hb39fc2d_0 defaults pip 20.1.1 py36_1 defaults portalocker 2.0.0 pypi_0 pypi prometheus-client 0.8.0 pypi_0 pypi promise 2.3 pypi_0 pypi prompt-toolkit 3.0.5 pypi_0 pypi protobuf 3.12.4 pypi_0 pypi psutil 5.7.0 py36h7b6447c_0 defaults ptyprocess 0.6.0 pypi_0 pypi pyarrow 1.0.0 pypi_0 pypi pyasn1-modules 0.2.8 pypi_0 pypi pycparser 2.20 py_2 defaults pydeck 0.4.1 pypi_0 pypi pygments 2.6.1 pypi_0 pypi pyparsing 2.4.7 pypi_0 pypi pyrsistent 0.16.0 pypi_0 pypi python 3.6.10 h7579374_2 defaults python-dateutil 2.8.1 py_0 defaults pytorch 1.5.0 py3.6_cuda9.2.148_cudnn7.6.3_0 pytorch pytorch-lightning 0.8.5 pypi_0 pypi pytz 2020.1 py_0 defaults pyyaml 5.3.1 pypi_0 pypi pyzmq 19.0.2 pypi_0 pypi readline 8.0 h7b6447c_0 defaults redispy 3.0.0 pypi_0 pypi regex 2020.7.14 pypi_0 pypi requests 2.24.0 pypi_0 pypi requests-oauthlib 1.3.0 pypi_0 pypi rouge-score 0.0.4 pypi_0 pypi s3transfer 0.3.3 pypi_0 pypi sacrebleu 1.4.13 pypi_0 pypi scikit-learn 0.23.1 py36h423224d_0 defaults scipy 1.5.2 pypi_0 pypi send2trash 1.5.0 pypi_0 pypi seqeval 0.0.12 pypi_0 pypi setuptools 49.2.1 pypi_0 pypi six 1.15.0 py_0 defaults smart-open 5.2.1 pypi_0 pypi smmap 3.0.4 pypi_0 pypi sqlite 3.32.3 h62c20be_0 defaults streamlit 0.64.0 pypi_0 pypi tabulate 0.8.9 pypi_0 pypi tensorboard 1.14.0 pypi_0 pypi tensorboard-plugin-wit 1.7.0 pypi_0 pypi tensorflow-datasets 3.2.1 pypi_0 pypi tensorflow-metadata 0.22.2 pypi_0 pypi termcolor 1.1.0 pypi_0 pypi terminado 0.8.3 pypi_0 pypi testpath 0.4.4 pypi_0 pypi threadpoolctl 2.1.0 pyh5ca1d4c_0 defaults tk 8.6.10 hbc83047_0 defaults toml 0.10.1 pypi_0 pypi toolz 0.10.0 pypi_0 pypi torchvision 0.6.0 py36_cu92 pytorch tornado 6.0.4 pypi_0 pypi tqdm 4.48.2 pypi_0 pypi traitlets 4.3.3 pypi_0 pypi transformers 3.0.2 pypi_0 pypi tzlocal 2.1 pypi_0 pypi urllib3 1.25.10 pypi_0 pypi validators 0.17.1 pypi_0 pypi watchdog 0.10.3 pypi_0 pypi wcwidth 0.2.5 pypi_0 pypi webencodings 0.5.1 pypi_0 pypi werkzeug 1.0.1 pypi_0 pypi wheel 0.34.2 py36_0 defaults widgetsnbextension 3.5.1 pypi_0 pypi wrapt 1.12.1 pypi_0 pypi xxhash 2.0.0 pypi_0 pypi xz 5.2.5 h7b6447c_0 defaults zipp 3.1.0 pypi_0 pypi zlib 1.2.11 h7b6447c_3 defaults zstd 1.4.5 h9ceee32_0 defaults
> 
> May you have a nice day! I will reply to your question further after I receive the email.

1、Thanks for  your reply, the `trees.pkl` is the example result in your repository `sota_end2end_parser/data/e2e/`.
2、And is this suitable for `Micro Chinese Discourse Treebank(MCDTB)` corpus? Because I have read your paper `Adversarial Learning for Discourse Rhetorical Structure Parsing` and the paper only mention `RST-DT` and `Connective Driven Discourse Treebank(CDTB)` corpus.

**Comment by zzlynx** [comment]
Hi! purelove4you,
    Seeing the following image, the "trees.pkl" contains all the parse trees and they are objects of the class rst_tree in the file "structure/rst_tree". I've provided the structure in the project, the solution is finding the reason why your running of pipeline.py cannot locate the directory "structure".
<img width="312" alt="1" src="https://user-images.githubusercontent.com/23730796/170589685-e6c7e445-5021-4938-914a-6e1a90dfb638.png">

For the question on "CDTB or MCDTB", actually, I only study micro discourse parsing based on the CDTB data. For the pre-trained model on Macro CDTB, you can send e-mails to our team member Feng Jiang for it.

May you have a wonderful day that is different from yesterday!

**Comment by SHADOWX-frank** [comment]
I have the same problem when I run pipeline.py

**AttributeError: 'GRU' object has no attribute '_flat_weights_names'**

How to solve this problem？

**Comment by NLP-Discourse-SoochowU** [comment]
I've been busy with graduating, getting married, and working since September last year and I'm so sorry I just saw your question today. This should be a problem with the version of the installation package. There should be a general solution to this problem on the Internet.

**Comment by SHADOWX-frank** [comment]
Thank you for your help, I have solved this problem by changing the version earlier

**Comment by tchewik** [comment]
The configuration that [worked for me](https://hub.docker.com/layers/tchewik/isanlp_zhang21/latest/images/sha256-df953ee850a54de57f6d585daaf44b005894a7bdd57224a42ad1bf4250e24b0d?context=explore):
allennlp==1.0.0
torch==1.3.1
transformers==3.0.2
Installed one-by-one in this exact order.

**Comment by cooper12121** [comment]
yeah,this is actually the problem of torch version, the 1.3.0 is ok

**Comment by cooper12121** [comment]
> The configuration that [worked for me](https://hub.docker.com/layers/tchewik/isanlp_zhang21/latest/images/sha256-df953ee850a54de57f6d585daaf44b005894a7bdd57224a42ad1bf4250e24b0d?context=explore): allennlp==1.0.0 torch==1.3.1 transformers==3.0.2 Installed one-by-one in this exact order.

excuse me ,there is a problem when i use torch==1.3.1,if i use cpu version of torch,there is no problem,but if i use gpu version of torch,the torch.load() will occurs Segmentation fault (core dumped), have you ever meet this ,thank you!

**Comment by tchewik** [comment]
> excuse me ,there is a problem when i use torch==1.3.1,if i use cpu version of torch,there is no problem,but if i use gpu version of torch,the torch.load() will occurs Segmentation fault (core dumped), have you ever meet this ,thank you!

Yes, it appears that the setup works properly only with Python 3.6. You can find more information in my [fork](https://github.com/tchewik/sota_end2end_parser).
